title: Pixels to Patients (P2P-CV) — WACV 2026
description: Bridging CV state-of-the-art with clinical impact
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins: [jekyll-include-cache, jekyll-feed]

defaults:
  - scope:
      path: ""
    values:
      layout: single
      toc: true
      toc_sticky: true
baseurl: "/p2p-cv-wacv26"

# Navigation
main:
  - title: Home
    url: "{{ site.baseurl }}/"
  - title: Call for Papers
    url: "{{ site.baseurl }}/cfp/"
  - title: Important Dates
    url: "{{ site.baseurl }}/dates/"
  - title: Invited Speakers
    url: "{{ site.baseurl }}/speakers/"
  - title: Organizers
    url: "{{ site.baseurl }}/team/"
  - title: Program
    url: "{{ site.baseurl }}/program/"
